### PR TITLE
Add firewall workaround

### PR DESCRIPTION
**Pull request by topaz2**
I'm behind the firewall blocking outbound default keyserver port, so I've added feature to specify custom port number.

### CODE REVIEW

**Comment by amaltson** [comment]
:+1:

**Comment by kisoku** [comment]
so what happens when I want to install 2 different apt repos that require different custom keyserver ports ?

**Comment by amaltson** [comment]
For me I found if you set the `key_proxy` it'll use port `80` for everything. This works for Enterprise firewalls.

**Comment by thommay** [comment]
I took #132 in favour of this, but thank you for your contribution.

**Pull request closed without merging**
